// <auto-generated />
using System;
using Baseline.ItemConfig.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Baseline.ItemConfig.Infra.Migrations
{
    [DbContext(typeof(ItemConfigDbContext))]
    [Migration("20260715131258_AddRootItemNumber")]
    partial class AddRootItemNumber
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Baseline.ItemConfig.Domain.HuntTypeLicenseYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MasterHuntTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MasterHuntTypeId", "Year")
                        .IsUnique();

                    b.ToTable("HuntTypeLicenseYears", (string)null);
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.Item", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ItemNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ItemYear")
                        .HasColumnType("int");

                    b.Property<Guid>("RootItemNumberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UiSubTabId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UiTabId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ItemId");

                    b.HasIndex("RootItemNumberId");

                    b.HasIndex("UiSubTabId");

                    b.HasIndex("UiTabId");

                    b.HasIndex("ItemYear", "ItemNumber")
                        .IsUnique();

                    b.ToTable("Item", (string)null);
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.MasterHuntType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MasterHuntTypes", (string)null);
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.Outlet", b =>
                {
                    b.Property<Guid>("OutletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OutletTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OutletId");

                    b.HasIndex("OutletTypeId");

                    b.ToTable("Outlet", (string)null);
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.OutletType", b =>
                {
                    b.Property<Guid>("OutletTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OutletTypeId");

                    b.ToTable("OutletType", (string)null);
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.OutletTypeItem", b =>
                {
                    b.Property<Guid>("OutletTypeItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OutletTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OutletTypeItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OutletTypeId", "ItemId")
                        .IsUnique();

                    b.ToTable("OutletTypeItem", (string)null);
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.RootItemNumber", b =>
                {
                    b.Property<Guid>("RootItemNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RootItemNumberId");

                    b.HasIndex("Number")
                        .IsUnique();

                    b.ToTable("RootItemNumber", (string)null);
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.UiSubTab", b =>
                {
                    b.Property<Guid>("UiSubTabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UiTabId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UiSubTabId");

                    b.HasIndex("UiTabId");

                    b.ToTable("UiSubTab", (string)null);
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.UiTab", b =>
                {
                    b.Property<Guid>("UiTabId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UiTabId");

                    b.ToTable("UiTab", (string)null);
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.HuntTypeLicenseYear", b =>
                {
                    b.HasOne("Baseline.ItemConfig.Domain.MasterHuntType", "MasterHuntType")
                        .WithMany("HuntTypeLicenseYears")
                        .HasForeignKey("MasterHuntTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterHuntType");
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.Item", b =>
                {
                    b.HasOne("Baseline.ItemConfig.Domain.RootItemNumber", "RootItemNumber")
                        .WithMany("Items")
                        .HasForeignKey("RootItemNumberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Baseline.ItemConfig.Domain.UiSubTab", "UiSubTab")
                        .WithMany("Items")
                        .HasForeignKey("UiSubTabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Baseline.ItemConfig.Domain.UiTab", "UiTab")
                        .WithMany("Items")
                        .HasForeignKey("UiTabId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RootItemNumber");

                    b.Navigation("UiSubTab");

                    b.Navigation("UiTab");
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.Outlet", b =>
                {
                    b.HasOne("Baseline.ItemConfig.Domain.OutletType", "OutletType")
                        .WithMany("Outlets")
                        .HasForeignKey("OutletTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutletType");
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.OutletTypeItem", b =>
                {
                    b.HasOne("Baseline.ItemConfig.Domain.Item", "Item")
                        .WithMany("OutletTypeItems")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Baseline.ItemConfig.Domain.OutletType", "OutletType")
                        .WithMany("OutletTypeItems")
                        .HasForeignKey("OutletTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("OutletType");
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.UiSubTab", b =>
                {
                    b.HasOne("Baseline.ItemConfig.Domain.UiTab", "UiTab")
                        .WithMany("UiSubTabs")
                        .HasForeignKey("UiTabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UiTab");
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.Item", b =>
                {
                    b.Navigation("OutletTypeItems");
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.MasterHuntType", b =>
                {
                    b.Navigation("HuntTypeLicenseYears");
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.OutletType", b =>
                {
                    b.Navigation("OutletTypeItems");

                    b.Navigation("Outlets");
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.RootItemNumber", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.UiSubTab", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.UiTab", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("UiSubTabs");
                });
#pragma warning restore 612, 618
        }
    }
}
