// <auto-generated />
using System;
using Baseline.ItemConfig.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Baseline.ItemConfig.Infra.Migrations
{
    [DbContext(typeof(ItemConfigDbContext))]
    [Migration("20260710020002_AddHuntTypeLicenseYear")]
    partial class AddHuntTypeLicenseYear
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Baseline.ItemConfig.Domain.HuntTypeLicenseYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MasterHuntTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MasterHuntTypeId", "Year")
                        .IsUnique();

                    b.ToTable("HuntTypeLicenseYears", (string)null);
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.MasterHuntType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MasterHuntTypes", (string)null);
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.HuntTypeLicenseYear", b =>
                {
                    b.HasOne("Baseline.ItemConfig.Domain.MasterHuntType", "MasterHuntType")
                        .WithMany("HuntTypeLicenseYears")
                        .HasForeignKey("MasterHuntTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MasterHuntType");
                });

            modelBuilder.Entity("Baseline.ItemConfig.Domain.MasterHuntType", b =>
                {
                    b.Navigation("HuntTypeLicenseYears");
                });
#pragma warning restore 612, 618
        }
    }
}
